hl.on("hyprland.start", function()
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("awww-daemon && awww img ~/.config/hypr/wallpaper.png")
	hl.exec_cmd("waybar & hyprlock")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("swaync")
end)
