applications:
  - name: kitty
    themes: ~/.config/hueshift/kitty/themes/
    components:
      - name: colors
        target:
          path: ~/.config/kitty/colors.conf
          type: link
    hooks:
      - stage: post
        cmd: pkill -SIGUSR1 kitty
  - name: waybar
    themes: ~/.config/hueshift/waybar/themes/
    components:
      - name: colors
        target:
          path: ~/.config/waybar/colors.css
          type: link
    hooks:
      - stage: post
        cmd: pkill waybar
      - stage: post
        cmd: waybar
        detach: true
  - name: hypr
    themes: ~/.config/hueshift/hypr/themes/
    components:
      - name: colors
        target:
          path: ~/.config/hypr/colors.conf
          type: link
      - name: wallpapers
        target:
          path: ~/.config/hypr/wallpaper.png
          type: link
    hooks:
      - stage: post
        cmd: hyprctl reload
      - stage: post
        cmd: killall hyprpaper && hyprpaper &
        detach: true
  - name: rofi
    themes: ~/.config/hueshift/rofi/themes/
    components:
      - name: colors
        target:
          path: ~/.config/rofi/colors.rasi
          type: link
  - name: nvim
    themes: ~/.config/hueshift/nvim/themes/
    components:
      - name: colors
        target:
          path: ~/.config/nvim/lua/themes/active.lua
          type: link
    hooks:
      - stage: post
        cmd: ./nvim/.scripts/reload.sh {{ theme }}
  - name: starship
    themes: ~/.config/hueshift/starship/themes/
    components:
      - name: colors
        target:
          path: ~/.config/starship.toml
          type: link
    hooks:
      - stage: post
        cmd: ./starship/.scripts/reload.sh
